# This workflow will release a Python package

name: Release

on:
  push:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'
    tags: [ 'v**' ]
  release:
    types: [ created ]
  #workflow_run:
  #  workflows: [ "Build" ]
  #  types: [ completed ]
  #  branches:
  #    - "releases/**"
  #    - '!releases/**-alpha'


jobs:
  build:
    #if: github.event_name != 'release'  # run when pushed, so don't need
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Setup sdist
      run: python setup.py sdist
    - name: Publish package
      #if: github.event_name == 'release' or github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true
        verbose: true
